### ISSUE TITLE
[Suggestion] Bigger health/armor numbers

### ISSUE THREAD

**Issue by adem4ik** [jekyllgrim/Alice-Toys-of-Madness#2]
Health/armor numbers look too small, even with increased HUD scale factor. I think numbers should be 2-3 times bigger. Here is the comparison with `uiscale = 5`:
![1](https://github.com/user-attachments/assets/fd17c16b-5dcd-40fe-8554-21ba719228e5)
![2](https://github.com/user-attachments/assets/77ec9380-966e-4f68-b252-99c418c815c1)

There is still a room for bigger uiscale, but it looks unplayable with `uiscale = 6` as the console text becomes too huge:
![Screenshot_Doom_20240805_004036](https://github.com/user-attachments/assets/cf27e36b-20cb-4900-8b4f-f9faaef70a4a)
![Screenshot_Doom_20240805_004121_01](https://github.com/user-attachments/assets/1f25448d-dc6f-44a0-ba5a-45675a77f95b)

**Comment by jekyllgrim** [comment]
I'll think about how this can be done. However, please note that you can adjust scale of console text and the HUD separately, they don't have to be controlled by the same option. Use individual scaling options instead of relying on UI scale:

![image](https://github.com/user-attachments/assets/4e9e31ef-25b5-4aa1-a8b2-2a4207db0fef)

**Comment by jekyllgrim** [comment]
Modified HUD to make armor/health numbers bigger in e6e25eb5639e38cdbfdaad289350c3d800e7f6f9. You can play a dev build or wait for 1.1.0 to release (should be soon).

![image](https://github.com/user-attachments/assets/467c46b7-8725-4094-9812-f6be7ee2e634)
