### ISSUE TITLE
Player model preview is missing in the Options menu

### ISSUE THREAD

**Issue by adem4ik** [jekyllgrim/Alice-Toys-of-Madness#4]
1. Go to the Options > Player Setup

Result: Player's model is missing

![изображение](https://github.com/user-attachments/assets/f3f55fcd-b387-4fc6-a899-f8b0497bd844)

**Comment by jekyllgrim** [comment]
Unfortunately, this is not _really_ fixable. The player actor is using a 3D model; GZDoom can't draw 3D models in UI scope, so if a player character has a 3D model attached, this element simply draws nothing.
In addition to this, this menu is in general not particularly functional with the mod. You can't change skins, since they don't work with 3D models. You also can't change player color because the model is not translateable (it's using truecolor textures incompatible with color translations).

I also can't replace this menu, because that can only be done by replacing the whole options menu, which can cause compatibility and other issues. So, for now, unfortunately, I don't have a solution for this. I'll be thinking about this, though.

**Comment by jekyllgrim** [comment]
8e66929d163e8f30e19e9a55496da62d910b1ac3 adds Alice's image. Not much else I can do, since showing a model would require too invasive changes to the game's menu, which is not in my plans (at least for now).

**Comment by adem4ik** [comment]
Looks great! Thank you.
![изображение](https://github.com/user-attachments/assets/7b148d6a-c33a-4ee6-a299-709bc46cfdc1)
